<a href="https://colab.research.google.com/github/samikshyasanskruti/DeepLearning-with-TesorFlow/blob/main/K_Means_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SAMIKSHYA SANSKRUTI**

**2341019634**

# ***UNSUPERVISED LEARNING***

**Import Libraries**

In [ ]:
import numpy as np
import pandas as pd

**Load Dataset**

In [ ]:
df=pd.read_csv("income.csv")
df

        Name  Age  Income($)
0        Rob   27      70000
1    Michael   29      90000
2      Mohan   29      61000
3     Ismail   28      60000
4       Kory   42     150000
5     Gautam   39     155000
6      David   41     160000
7     Andrea   38     162000
8       Brad   36     156000
9   Angelina   35     130000
10    Donald   37     137000
11       Tom   26      45000
12    Arnold   27      48000
13     Jared   28      51000
14     Stark   29      49500
15    Ranbir   32      53000
16    Dipika   40      65000
17  Priyanka   41      63000
18      Nick   43      64000
19      Alia   39      80000
20       Sid   41      82000
21     Abdul   39      58000

**Drop columns**

In [ ]:
df_1=df.drop(columns=['Name'])
df_1

    Age  Income($)
0    27      70000
1    29      90000
2    29      61000
3    28      60000
4    42     150000
5    39     155000
6    41     160000
7    38     162000
8    36     156000
9    35     130000
10   37     137000
11   26      45000
12   27      48000
13   28      51000
14   29      49500
15   32      53000
16   40      65000
17   41      63000
18   43      64000
19   39      80000
20   41      82000
21   39      58000

**Assume you have a dataframe df.Randomly select k centroids from df.**

In [ ]:
centroids=np.array(df_1.sample(n=3,random_state=42))
centroids

array([[    27,  70000],
       [    28,  51000],
       [    36, 156000]])

In [ ]:
np.linalg.norm(centroids,axis=1)

array([ 70000.00520714,  51000.00768627, 156000.00415385])

In [ ]:
np.linalg.norm(df_1-centroids[0],axis=1)

array([    0.        , 20000.0001    ,  9000.00022222, 10000.00005   ,
       80000.00140625, 85000.00084706, 90000.00108889, 92000.00065761,
       86000.00047093, 60000.00053333, 67000.00074627, 25000.00002   ,
       22000.        , 19000.00002632, 20500.00009756, 17000.00073529,
        5000.01689997,  7000.01399999,  6000.0213333 , 10000.0072    ,
       12000.00816666, 12000.006     ])

In [ ]:
L=np.argmin(np.array([np.linalg.norm(df_1-centroids[i],axis=1) for i in range(3)]).T,axis=1)

L

array([0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1])

In [ ]:
updated_centroids = np.array([df_1[L == i].mean(axis=0) for i in range(3)])
updated_centroids

array([[3.61250000e+01, 7.18750000e+04],
       [2.98571429e+01, 5.20714286e+04],
       [3.82857143e+01, 1.50000000e+05]])

In [ ]:
def update_labels(data, centroids):
    distances = np.array([np.linalg.norm(data - centroid, axis=1) for centroid in centroids]).T
    labels = np.argmin(distances, axis=1)
    return labels

In [ ]:
def k_means_clustering(data, k, iterations=100):
  df_copy=data.copy()
  centroids=np.array(df_copy.sample(n=k,random_state=42))
  for _ in range(iterations):
    L=update_labels(df_copy,centroids=centroids)
    centroids=np.array([np.mean(df_copy[L==i],axis=0) for i in range(k)])
  return centroids,L

L,centroids=k_means_clustering(df_1,k=3,iterations=2)
print(L)
print(centroids)

[[3.71428571e+01 7.34285714e+04]
 [2.97500000e+01 5.31875000e+04]
 [3.82857143e+01 1.50000000e+05]]
[0 0 1 1 2 2 2 2 2 2 2 1 1 1 1 1 0 0 0 0 0 1]